### ISSUE TITLE
Good stuff - minor tweaks

### ISSUE THREAD

**Issue by billjinks** [ciarant/vscode-structurizr#1]
Ciaran, good extension and very similar to what I also did last weekend (but didn't publish). A couple of items for consideration:

- I restricted keyword.control to only "\\b(workspace|model|views|!include)\\b"
- I used keyword.support.type for the other structurizr nouns, and accepted both versions of the case, e.g. "\\b(software[s,S]ystem|system[l,L]andscape)\\b" etc.

Thanks for sharing.

**Comment by ciarant** [comment]
Thanks Bill - good points. One question on the second point above - you suggest using "keyword.support.type" for other Structurizr nouns. Did you, by chance, mean "support.type" instead?

**Comment by ciarant** [comment]
Needed to get this done on Sunday - otherwise I might not get back to it again for a few days. Bill, I've pushed fixes for your suggestions, bumped the version to 0.0.3, and pushed to the VSCode Marketplace. Thanks again!
