### ISSUE TITLE
Highlightning for whole words only ?

### ISSUE THREAD

**Issue by ncasaux** [ciarant/vscode-structurizr#8]
Hello,

Could it be possible to highlight only the words which are "alone" ?

Example 1: I would like that the "model" word **not** to be highlighted, as it's a folder in my case.
![image](https://user-images.githubusercontent.com/16475875/199686254-d53a2bd0-ec97-4773-9599-4d4e70ff43b4.png)

Example 2:  I would like that the yellow "systemLandscape" word **not** to be highlighted, as it's a part of my identifier.
![image](https://user-images.githubusercontent.com/16475875/199686727-c46585dd-fd9a-4160-a177-6c6cd1f1246d.png)

Thanks in advance!

**Comment by ciarant** [comment]
Thanks for reporting this. Fixed in 0.0.9.

**Comment by ncasaux** [comment]
Wonderful ! 😄 
![image](https://user-images.githubusercontent.com/16475875/199771020-b92b05e4-bc10-491f-b352-5d326b5c65d2.png)

Thanks you!
