### ISSUE TITLE
Extension unavailable in VSCodium

### ISSUE THREAD

**Issue by Riduidel** [ciarant/vscode-structurizr#9]
Seems like your wonderful extension is not available in VSCodium extension store.

See https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace for more details

**Comment by ciarant** [comment]
Done - https://open-vsx.org/extension/ciarant/vscode-structurizr
Just waiting on my namespace to get verified.

First time hearing about VSCodium, btw - thank you!
